name: check-all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run check:js
      - run: npm run check:types
